version: '3'
services:
  server:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://climatefuture_user@postgres/climatefuture
      - GOOGLE_MAPS_PLATFORM_KEY
      - NODE_ENV=development
      - PORT=3001
    expose:
      - 3001
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/server
      # Don't sync node_modules from host
      - /usr/server/node_modules
  postgres:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_DB: climatefuture
      POSTGRES_USER: climatefuture_user
    volumes:
      # Load schema and seed data when postgres is initialized
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
