apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://climatefuture_user@postgres/climatefuture
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3001"
        image: kevinsqi/climatefuture
        name: server
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
status: {}
